### ISSUE TITLE
WebSharper.Html.Server.Web.Control is lost

### ISSUE THREAD

**Issue by Micha-kun** [dotnet-websharper/html#1]
Hello, today I upgraded to WebSharper 3.5 and, after installing this Nuget, I have some controls using WebSharper.Html.Server.Web.Control because I could do Server-side Web Controls and now it disappeared. Can you put it back, please?

**Comment by granicz** [comment]
Can you paste the code that broke?  Be sure to add a reference to the `WebSharper.Html` NuGet as well, as the old HTML language has been split off into that package.

**Comment by Micha-kun** [comment]
```
open WebSharper
open WebSharper.Html.Server

type HelloWorldControl() =
    inherit Web.Control()

    override this.Element =
        Div [Text "Hello world!"]
```

This file in concrete:

https://github.com/intellifactory/websharper/blob/36188722cf1555bf5479bd7dab789b9fee602ab9/src/htmllib/WebSharper.Html.Server/Control.fs

**Comment by Tarmil** [comment]
This is indeed an oversight, I am adding it now.

**Comment by granicz** [comment]
This is now on NuGet.  Let us know if something is still out of place.
